### PR TITLE
Added config option for tag file name. Made .tags the default.

### PR DESCRIPTION
**Pull request by baelter**
Kinda speaks for it self.

### CODE REVIEW

**Comment by baelter** [comment]
fixes #33

**Comment by Evmorov** [comment]
This pull request is here for quite long time. I think you should be one of the owner of this repo.

**Comment by baelter** [comment]
Maybe :) Ping! @weskinner

**Comment by trainto** [comment]
I think It would be nice if this is merged.
@weskinner might've stopped developing this package anymore.. I don't know..

**Comment by baelter** [comment]
Yeah seems like it. I started using tern-js instead of ctags though..

**Comment by trainto** [comment]
Unfortunately I mostly develop C++ library using ATOM, I need CTags.. :(

**Comment by ThomasTesla** [comment]
+1

**Pull request merged**
